# Generated by Django 5.2.5 on 2025-08-13 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='description',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='title',
        ),
        migrations.AddField(
            model_name='quiz',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testapp.category'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='difficulty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testapp.difficulty'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='name',
            field=models.CharField(default='Java', max_length=100),
        ),
        migrations.AddField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(to='testapp.question'),
        ),
    ]
